<%
def get_mysql_password(file)
  `cat #{file} 2>>/dev/null | grep password`.split('=')[1].strip
end
%>

mysql: &mysql
  adapter: mysql2
  username: williams
  password: <%= get_mysql_password("#{ENV['HOME']}/.my.cnf") %>
  host: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development: #&development
  <<: *mysql
  database: raven_development

test: #&test
  <<: *mysql
  database: raven_test

production: #&production
  <<: *mysql
  database: raven_production

